import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import type { LayoutBaseProps } from "@/utils";



const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
    title: "WBS Creator",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: LayoutBaseProps) {
    return (
        <html lang="en">
            <head>
                {/* Bootstrap Stylesheet */}
                <link
                    rel="stylesheet"
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
                    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
                    crossOrigin="anonymous"
                />
                {/* Bootstrap Icons */}
                <link
                    rel="stylesheet"
                    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
                />
            </head>
            <body className={inter.className}>
                <main className="container">
                    {children}
                </main>
            </body>
        </html>
    );
}
